# name: Update Minions
# on:
#   schedule:
#     - cron: '0 0 * * *'

# jobs:
#   update_minions:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Update Cards
#         run: |
#           npm install
#           npm run update-cards
      
#       - name: Add and commit
#         uses: EndBug/add-and-commit@v9 # You can change this to use a specific version.
#         with:
#           # The arguments for the `git add` command (see the paragraph below for more info)
#           # Default: '.'
#           add: 'src'

#           # The name of the user that will be displayed as the author of the commit.
#           # Default: depends on the default_author input
#           author_name: Jim Liu

#           # The email of the user that will be displayed as the author of the commit.
#           # Default: depends on the default_author input
#           author_email: jim.liu.95@gmail.com

#           # The local path to the directory where your repository is located. You should use actions/checkout first to set it up.
#           # Default: '.'
#           cwd: './path/to/the/repo'

#           # The message for the commit.
#           # Default: 'Commit from GitHub Actions (name of the workflow)'
#           message: 'Updating minion list via Github Actions'

#           # The way the action should handle pathspec errors from the add and remove commands. Three options are available:
#           # - ignore -> errors will be logged but the step won't fail
#           # - exitImmediately -> the action will stop right away, and the step will fail
#           # - exitAtEnd -> the action will go on, every pathspec error will be logged at the end, the step will fail.
#           # Default: ignore
#           pathspec_error_handling: ignore